///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesLauncherIcon = 'assets/images/launcher_icon.png';
  static const String imagesLauncherIconMonochrome =
      'assets/images/launcher_icon_monochrome.png';
  static const String splashSplash = 'assets/images/splash/splash.png';
}
